#### Find one cell that its neg_low is above vmzoro and one cell that its neg_low is above 0; look at the trace data for both on dvt.
Use data set: 
1. 170109_ENG-SYS_02_wobbuffet_WAV13R07C12_cycle1 (check is existed: /experiments/vmzero_end/cell_anno/vmzero_end Dataset {131072) 
2. 170124_SIG-A_03_blastoise_WAV06R05C15  (check is existed: /experiments/vmzero_end/cell_anno/vmzero_end Dataset {131072) 
3. 170206_TAG_01_caterpie_WAV07R10C15 (CVC mode ==> vmzero_end is NOT existed, why?)

In [1]:
from os.path import abspath, dirname, join
import numpy as np
import matplotlib.pyplot as plt

import ac_analysis
from ac_analysis.model.annotations import load_from_h5

### 1) Load the annotation files and show the interested annotations

In [2]:
# 1) 170109_ENG-SYS_02_wobbuffet_WAV13R07C12_cycle1
#anno_path="/mnt/AGZ_Home_vmwin10/workspace_pOD/genia/Andrew/170109_ENG-SYS_02_wobbuffet_WAV13R07C12_cycle1/P_00_170110023618_ggc3-keeper_ac-analysis_v11.19.1/annotations.h5"

# 2) 170124_SIG-A_03_blastoise_WAV06R05C15
#anno_path="/mnt/AGZ_Home_vmwin10/workspace_pOD/genia/Andrew/170124_SIG-A_03_blastoise_WAV06R05C15/annotations.h5"

#Script for this one ==>
#anno_path="/home/genia/rigdata/blastoise/170124_SIG-A_03_blastoise_WAV06R05C15/\
#P_00_170124230837_ggc3-keeper_ac-analysis_v11.19.1/annotations.h5"
#

anno_path = "/home/genia/azhang/GPU_TEST_HOME/data/170124_SIG-A_03_blastoise_WAV06R05C15/\
P_00_170124230837_ggc3-keeper_ac-analysis_v11.19.1/annotations.h5"


#anno_path = "/home/genia/rigdata/crobat/170120_SW_03_crobat_WAV05R07C13_cycle1/P_12_170201223402_spore1-master_ac-analysis_v11.21.1/annotations.h5"

annos = load_from_h5(anno_path)
print "annos ==> ", annos

annos ==>  <ac_analysis.model.annotations_v2.Annotations_v2 object at 0x7f72621aaf50>


In [3]:
neg_low, units = annos.get_rep_annotation('neg_low') # Enthough enable us to grab neg_low matrix shape = (cells, reps)
print "neg_low ==> ",  neg_low, units
print "\nneg_low.shape ==> ", neg_low.shape
print "\nneg_low.size ==> ", neg_low.size # rows * columns

neg_low ==>  [[ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 ..., 
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]
 [ nan  nan  nan ...,  nan  nan  nan]] ADC

neg_low.shape ==>  (131072, 31)

neg_low.size ==>  4063232


In [4]:
cells = annos.cells  #grab all cells
print "cells ==> ", cells
print "\ncells.shape ==> ", cells.shape
print "\ncells.size ==> ", cells.size 

cells ==>  ['b00c0000' 'b00c0001' 'b00c0002' ..., 'b15c8189' 'b15c8190' 'b15c8191']

cells.shape ==>  (131072,)

cells.size ==>  131072


### 2. Filter for neg_low

In [10]:
# Remove rows with only nan and zero 
#(probably dont want to just remove zeros, why?)
#mask = np.all(np.isnan(neg_low) | np.equal(neg_low, 0), axis=1) 
print "This mask only removes cells that have no reps of data. If a cell has even one rep of neg_low value recorded we keep the cell"
# Filter cells that don't complete sequencing waveform 
mask = np.all(np.isnan(neg_low), axis=1)
print "mask is ==> ", mask

filt_neg_low = neg_low[~mask]   #only get cells where neg_low is not all nan or all zero
print "\nfilt_neg_low is: ", filt_neg_low

filt_cells = cells[~mask]  #get cell names based on neg_low mask 
print "\nfilt_cells is: ", filt_cells



This mask only removes cells that have no reps of data. If a cell has even one rep of neg_low value recorded we keep the cell
mask is ==>  [ True  True  True ...,  True  True  True]

filt_neg_low is:  [[-10.85306072 -10.28666973 -10.69818687 ..., -25.76595116 -25.78050232
  -25.7927494 ]
 [ -2.96160626  -1.97020257  -1.97036946 ...,  -1.97030938  -1.97037399
   -1.97030687]
 [ -6.67061424  -7.02709198  -7.53554487 ...,          nan          nan
           nan]
 ..., 
 [-77.29393005 -84.30439758 -84.58358002 ...,          nan          nan
           nan]
 [-87.52383423 -93.97598267 -95.60056305 ...,          nan          nan
           nan]
 [-75.48808289 -84.0631485  -96.71679688 ...,          nan          nan
           nan]]

filt_cells is:  ['b00c0392' 'b00c0480' 'b00c0509' ..., 'b15c7996' 'b15c7997' 'b15c7999']


In [ ]:
# 2-1 

### 2-1 A test case to check the corretness

In [13]:
# Test one cell trace: such as b15c7996 and b02c7334
print "\n=================\nMISC: Verify a few cells' value for b15c7996 and b02c7334 \n================== "
#neg_low_cell = neg_low[cells == 'b15c7996']
neg_low_cell = neg_low[cells == 'b02c7334']
print "Below we can see that cell was deactivated after 3 reps, so only 3 neg_low values were recorded."
print "In order to keep numpy matrix structure, the remaining values were recorded as nan???"
print "\nneg_low_cell is: ", neg_low_cell  # What does these 3 values?




MISC: Verify a few cells' value for b15c7996 and b02c7334 
Below we can see that cell was deactivated after 3 reps, so only 3 neg_low values were recorded.
In order to keep numpy matrix structure, the remaining values were recorded as nan???

neg_low_cell is:  [[-18.48287201 -17.6192112  -15.18126583 -12.58522701 -16.29192734
  -16.31523514 -15.88560581 -13.02407742 -14.00270081 -14.15161037
  -14.68091679 -15.05156231 -15.79098701 -16.93075562 -20.03195381
  -21.16149521 -21.6505394  -21.98173332 -24.4615097  -25.68001747
  -19.80051231          nan          nan          nan          nan
           nan          nan          nan          nan          nan
           nan]]


### 3. Get oc_calibration_vmzero

In [14]:
# 1) Read oc_calibration_vmzero
vmzeros, unit = annos.get_cell_annotation('oc_calibration_vmzero')
print "1) vmzeros ==> ", vmzeros, unit

# 2) Filted vmzero that elimited the nan, etc??
filt_vmzeros = vmzeros[~mask]
#plt.hist(filt_vmzeros, bins=100); plt.show()  #plot to show vmzeoro distribution
print "\n2) filt_vmzeros ==> ",  filt_vmzeros 

# 3 what you have is neg_low minus vmzero:
#    Get flatten matrix (numpy.matrix.flatten), 
#    See: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.flatten.html
#       https://plot.ly/numpy/ravel/

# now what you have is neg_low minus vmzero
flat_filt_neg_low = np.ravel(filt_neg_low)  #flatten matrix to array to do subtraction of vmzero 
print "3-1) flat_filt_neg_low ==> ", flat_filt_neg_low

# Feb 14. Conner fixed this logic by commentting out the following line:
#print flat_filt_neg_low.shape
#neg_low_minus_vmzero = (filt_neg_low - filt_vmzeros[:, np.newaxis])

neg_low_minus_vmzero = filt_neg_low

#print "ACTUAL FIRST ROW", neg_low_minus_vmzero[0]


#####################
#print "EXPECTED FIRST ROW" , filt_neg_low[0] - filt_vmzeros[0]

#sanity check for sign 
# plt.hist(filt_vmzeros, bins = 20); plt.show()

#confirm proper shape
print "3-3) neg_low_minus_vmzero.shape ==> ", neg_low_minus_vmzero.shape
print "3-4) flat_filt_neg_low.shape ==> ",  flat_filt_neg_low.shape

# Finally, give a value, such as : > 0, > 4, or > 5:
# How to decide? Actually we want to look for a positive number. For example, if vmzero is 120 and neg low goes to 130"
#"above" vmzero, then neg_low - vmzero will be positive e.g. 10. 


print "\n==============="
print "neg_low_minus_vmzero is: ", neg_low_minus_vmzero

print "\n==============="
print "\nneg_low_minus_vmzero.size is: ", neg_low_minus_vmzero.size

print "\n==============="
print "\nneg_low_minus_vmzero.shape is: ", neg_low_minus_vmzero.shape

1) vmzeros ==>  [ nan  nan  nan ...,  nan  nan  nan] ADC

2) filt_vmzeros ==>  [  95.28665161  112.97035217  124.0042038  ...,  103.78548431  112.5655899
  121.89308929]
3-1) flat_filt_neg_low ==>  [-10.85306072 -10.28666973 -10.69818687 ...,          nan          nan
          nan]
3-3) neg_low_minus_vmzero.shape ==>  (68485, 31)
3-4) flat_filt_neg_low.shape ==>  (2123035,)

neg_low_minus_vmzero is:  [[-10.85306072 -10.28666973 -10.69818687 ..., -25.76595116 -25.78050232
  -25.7927494 ]
 [ -2.96160626  -1.97020257  -1.97036946 ...,  -1.97030938  -1.97037399
   -1.97030687]
 [ -6.67061424  -7.02709198  -7.53554487 ...,          nan          nan
           nan]
 ..., 
 [-77.29393005 -84.30439758 -84.58358002 ...,          nan          nan
           nan]
 [-87.52383423 -93.97598267 -95.60056305 ...,          nan          nan
           nan]
 [-75.48808289 -84.0631485  -96.71679688 ...,          nan          nan
           nan]]


neg_low_minus_vmzero.size is:  2123035


neg_low_minus_vm

In [10]:
neg_low_minus_vmzero

array([[-10.85306072, -10.28666973, -10.69818687, ..., -25.76595116,
        -25.78050232, -25.7927494 ],
       [ -2.96160626,  -1.97020257,  -1.97036946, ...,  -1.97030938,
         -1.97037399,  -1.97030687],
       [ -6.67061424,  -7.02709198,  -7.53554487, ...,          nan,
                 nan,          nan],
       ..., 
       [-77.29393005, -84.30439758, -84.58358002, ...,          nan,
                 nan,          nan],
       [-87.52383423, -93.97598267, -95.60056305, ...,          nan,
                 nan,          nan],
       [-75.48808289, -84.0631485 , -96.71679688, ...,          nan,
                 nan,          nan]], dtype=float32)

### Plot the histogram for the neg_low_minus_vmzero:

In [ ]:
#plt.hist()

plt.hist(neg_low_minus_vmzero, bins=np.arange(-50,200,5), label = 'neg_low_minus_vmzero', color='b', alpha=0.5, lw=0.1)

plt.legend()
plt.title("neg_low_minus_vmzero")



### 3-1 Test the logic (neg_low_minus_vmzero > 0)

In [13]:
print '====== Final ======='
final_mask = np.any(neg_low_minus_vmzero > 0, axis=1)  # < -265
print "FINAL mask", final_mask.shape
print "Filt cells", filt_cells.shape

print "\nMISC Confirmation"
print "-------------------"
print "final_mask ==> ", final_mask
print "length of final_mask ==> ", len(final_mask)
print "filt_cells.shape    ==>  ",filt_cells.shape

print '\n====== Final Result ======='
final_filt_cells = filt_cells[final_mask]
print "Final Targeted Filted Cells ==> ", final_filt_cells



====== Final =======
FINAL mask (68485,)
Filt cells (68485,)

MISC Confirmation
-------------------
final_mask ==>  [False False False ..., False False False]
length of final_mask ==>  68485
filt_cells.shape    ==>   (68485,)

====== Final Result =======
Final Targeted Filted Cells ==>  ['b03c0958' 'b03c1036' 'b03c1053' 'b03c1711' 'b04c0233' 'b04c0343'
 'b04c0348' 'b04c0359' 'b04c0361' 'b04c0362' 'b04c0365' 'b04c0373'
 'b04c0488' 'b04c0493' 'b04c0494' 'b04c0495' 'b04c0496' 'b04c0501'
 'b04c0502' 'b04c0507' 'b05c0258' 'b05c0289' 'b05c0293' 'b05c7708'
 'b05c7823' 'b06c7732' 'b06c7792' 'b07c0478' 'b07c8056' 'b07c8104'
 'b08c0432' 'b08c0437' 'b08c0464' 'b08c0466' 'b08c0562' 'b08c0590'
 'b08c0687' 'b09c7265' 'b11c0100' 'b11c8127' 'b11c8129' 'b11c8130'
 'b11c8131' 'b11c8132' 'b11c8133' 'b11c8135' 'b12c0460' 'b12c0463'
 'b12c0502' 'b12c0546' 'b12c0548' 'b12c0585' 'b12c0586' 'b12c0587'
 'b12c7450' 'b13c0074' 'b13c0195' 'b13c0277' 'b13c0289' 'b13c0295'
 'b13c0311' 'b14c0125' 'b14c0126' 'b14c240

### 3-2 A test the logic using various combinations (neg_low_minus_vmzero <  0; < -10, -50, -200, etc)

In [12]:
print '====== Final ======='
final_mask = np.any(neg_low_minus_vmzero < -105, axis=1)  # < -265
print "FINAL mask", final_mask.shape
print "Filt cells", filt_cells.shape

final_filt_cells = filt_cells[final_mask]
print "Final Targeted Filted Cells ==> ", final_filt_cells

print "\nMISC Confirmation"
print "-------------------"
print "final_mask ==> ", final_mask
print "length of final_mask ==> ", len(final_mask)
print "filt_cells.shape    ==>  ",filt_cells.shape



====== Final =======
FINAL mask (68485,)
Filt cells (68485,)
Final Targeted Filted Cells ==>  ['b00c0621' 'b00c0722' 'b00c1401' 'b00c1439' 'b00c1587' 'b00c1657'
 'b00c1725' 'b00c1738' 'b00c1777' 'b00c1805' 'b00c1854' 'b00c1940'
 'b00c1982' 'b00c2061' 'b00c2166' 'b00c2403' 'b00c2522' 'b00c2608'
 'b00c2736' 'b00c2804' 'b00c3169' 'b00c3408' 'b00c3714' 'b00c4164'
 'b00c4921' 'b00c5183' 'b00c5437' 'b00c5710' 'b00c6067' 'b00c6446'
 'b00c6516' 'b00c6532' 'b00c7200' 'b00c7340' 'b00c7505' 'b00c7554'
 'b00c7571' 'b00c7653' 'b00c7989' 'b01c1094' 'b01c1195' 'b01c1216'
 'b01c1221' 'b01c1243' 'b01c1307' 'b01c1376' 'b01c1512' 'b01c1632'
 'b01c3122' 'b01c3941' 'b01c5248' 'b01c5451' 'b01c6010' 'b01c6013'
 'b01c6080' 'b01c6198' 'b01c6223' 'b01c6314' 'b01c6315' 'b01c6334'
 'b01c6463' 'b01c6574' 'b01c6580' 'b01c6600' 'b01c6634' 'b01c6761'
 'b01c6831' 'b01c7284' 'b01c7286' 'b01c7306' 'b01c7442' 'b01c7488'
 'b01c7494' 'b01c7770' 'b02c0715' 'b02c0757' 'b02c0838' 'b02c0847'
 'b02c0850' 'b02c0860' 'b02c1019' '

In [163]:
# Check cell b04c1191 and b11c4246 on the ac-dvt

### 4. Finally, calculate the rep(s)  and see on ac-dvt

#### MISC, a few other np functions 

In [151]:
np.where(neg_low_minus_vmzero < -265)[0]

# This function is to find the rep parameter and time
# array([18871, 48664]) ==> Number of the sameple
# 18871: dot (timing) 
# Find the total # of the dots, and 

array([18871, 48664])

In [164]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x` and `y` need to have the same
        shape as `condition`.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are 1-D, `wh

#### MISC: Find the rep numbers?

In [152]:
# Here might be the logic

cells = [['a'], ['b']] #This would be your array of cells 
x = np.array([[1,2,3], [1,4,5]])  #this would be your neg low 
x = x[cells != 'b'] 
np.where(x > 3)

/usr/local/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:5: DeprecationWarning: using a boolean instead of an integer will result in an error in the future


(array([1, 2]),)